console.log("hey")
document.querySelector('.cross').style.display='none';
document.querySelector('.menu').addEventListener("click",()=>{
    document.querySelector('.sidebar').classList.toggle('sidebarGo');
    if(document.querySelector('.sidebar').classList.toggle('sidebarGo')){
        document.querySelector('.menu').style.display='inline'
        document.querySelector('.cross').style.display='none'
    }
    else{
        document.querySelector('.menu').style.display='none'
        document.querySelector('.cross').computedStyleMap.display='inline'
    }
    })
